name: Basic CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run application check script
        run: |
          cd app
          chmod +x check_app.sh
          ./check_app.sh
          echo ${{ secrets.FAKE_API_TOKEN }}

      - name: Display index.html content
        run: cat app/index.html
